name = "QIPresolve"
uuid = "33dde124-04a6-4be8-8b9e-2121c91ea20b"
authors = ["Jan-Erik Hein <janerik.hein@gmail.com>"]
version = "1.0.0-DEV"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
JuMP = "1.29.4"
MathOptInterface = "1.48.0"
julia = "1.11"
