name = "QIPresolve"
uuid = "33dde124-04a6-4be8-8b9e-2121c91ea20b"
authors = ["Jan-Erik Hein <janerik.hein@gmail.com>"]
version = "1.0.0-DEV"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"

[compat]
Cairo = "1.1.1"
Compose = "0.9.6"
Fontconfig = "0.4.1"
GraphPlot = "0.6"
Graphs = "1"
JuMP = "1.29.4"
MathOptInterface = "1.48.0"
Random = "1.11.0"
SimpleWeightedGraphs = "1.5.1"
julia = "1.11"
